server {
    listen 1973;
    root /dist;

    location / {
        autoindex on;
        sendfile   on;
        sendfile_max_chunk 1m;
        tcp_nopush on;
        keepalive_timeout 65;
        add_header Access-Control-Allow-Origin *;
    }

    location /3d_data {
        autoindex on;
        sendfile   on;
        sendfile_max_chunk 1m;
        tcp_nopush on;
        keepalive_timeout 65;
        add_header Access-Control-Allow-Origin *;
        root /data;
    }

    location /sound_data {
        autoindex on;
        sendfile   on;
        sendfile_max_chunk 1m;
        tcp_nopush on;
        keepalive_timeout 65;
        add_header Access-Control-Allow-Origin *;
        root /data;
    }
}