use crate::crack_worker::WorkerMessage;
use serde::{Deserialize, Serialize};

/// Marker trait implemented by a type representing an API group.
///
/// Each group has a static `GROUP` identifier (e.g., `"WorkerApi"`).
pub trait ApiGroupDecl {
    /// The static name of this API group.
    const GROUP: &'static str;
}

/// Trait providing static metadata about the methods in an API group.
///
/// Implemented by the `declare_api_group2!` macro for the group's
/// zero-sized type.
pub trait ApiGroupMethods {
    /// Returns the group's static name (same as `ApiGroupDecl::GROUP`).
    fn grp_name(&self) -> &'static str;
    /// Returns a slice of [`ApiMethodInfo`] describing each method.
    fn method_infos(&self) -> &'static [ApiMethodInfo];
}

/// Extension of [`ApiGroupMethods`] that also provides the executable
/// implementations for each method.
///
/// Implemented by `implement_api_group2!` after the user supplies the
/// implementation functions.
pub trait ApiGroupImpls: ApiGroupMethods {
    /// Returns a slice of [`ApiMethodImpl`] containing the callable
    /// wrappers for each method.
    fn method_impls(&self) -> &'static [ApiMethodImpl];
}

/// Zero-sized type carrying only a group name.
///
/// Used internally by the macro machinery when a full group implementation
/// is not yet available (e.g., in `declare_api_group2!`).
#[derive(Clone, Copy, Debug)]
pub struct ApiGroupDeclStatic {
    /// The static group name.
    pub group: &'static str,
}

/// Trait implemented by each concrete API method type.
///
/// Generated by the `declare_api_method_before2!` macro. It associates:
/// - `NAME`: the method's static name (e.g., `"Ping"`).
/// - `Grp`: the group type implementing [`ApiGroupDecl`].
/// - `Arg`: the serialized argument type (must be `Clone + Debug + Serialize + Deserialize + Send + 'static`).
/// - `Ret`: the serialized return type (must be `Debug + Serialize + Deserialize + Send + 'static`).
pub trait ApiMethodDecl {
    /// Static method name.
    const NAME: &'static str;
    /// The API group this method belongs to.
    type Grp: ApiGroupDecl;
    /// Argument type for the RPC call.
    type Arg: Clone + std::fmt::Debug + Serialize + for<'a> Deserialize<'a> + 'static + Send;
    /// Return type for the RPC call.
    type Ret: std::fmt::Debug + Serialize + for<'a> Deserialize<'a> + 'static + Send;

    /// Returns the fully-qualified method name as `"Group.Method"`.
    fn fullname() -> String {
        let a = <Self::Grp as ApiGroupDecl>::GROUP;
        let b = Self::NAME;
        format!("{a}.{b}")
    }

    /// Wraps a user-provided async function into the worker's message
    /// processing pipeline.
    ///
    /// This handles:
    /// - Deserializing the argument from `postcard` bytes.
    /// - Calling the user function and measuring execution time.
    /// - Serializing the result (or error) back to `postcard` bytes.
    /// - Constructing a `WorkerMessage` response with timing diagnostics.
    ///
    /// The returned future is boxed and `Send` so it can be spawned on the
    /// worker runtime.
    #[allow(clippy::type_complexity)]
    fn wrap_impl(
        _func: fn(
            Self::Arg,
        ) -> std::pin::Pin<
            Box<dyn futures::Future<Output = anyhow::Result<Self::Ret>> + Send>,
        >,
        msg: WorkerMessage,
    ) -> std::pin::Pin<Box<dyn futures::Future<Output = WorkerMessage> + Send>> {
        let msg_id = msg.msg_id;
        let arg = postcard::from_bytes::<Self::Arg>(&msg.msg_content);

        // let arg = post
        // let ret = func(arg);
        // let v = postcard::to_vec(value)
        use futures::FutureExt;
        async move {
            let arg = match arg {
                Ok(o) => o,
                Err(e) => {
                    return WorkerMessage {
                        msg_id,
                        msg_type: "error_deserialize_arg".to_string(),
                        msg_content: format!("{e:#?}").as_bytes().to_vec(),
                    };
                }
            };
            let start = _crack_utils::get_timestamp_now_ms();
            let ret = _func(arg).await;
            let elapsed_func = _crack_utils::get_timestamp_now_ms() - start;

            let start_serialize = _crack_utils::get_timestamp_now_ms();
            let ret: Result<<Self as ApiMethodDecl>::Ret, String> =
                ret.map_err(|e| format!("{e:#?}"));

            let msg_content: Vec<u8> = match postcard::to_stdvec(&ret) {
                Ok(m) => m,
                Err(e) => {
                    return WorkerMessage {
                        msg_id,
                        msg_type: "error_serialize_ret".to_string(),
                        msg_content: format!("{e:#?}").as_bytes().to_vec(),
                    };
                }
            };
            let elapsed_serialize = _crack_utils::get_timestamp_now_ms() - start_serialize;
            tracing::debug!(
                "Worker: API call {} took run={} ms, serialize={} ms (size={} bytes)",
                Self::fullname(),
                elapsed_func,
                elapsed_serialize,
                msg_content.len()
            );

            WorkerMessage {
                msg_id,
                msg_type: "return".to_string(),
                msg_content,
            }
        }
        .boxed()
    }
}

/// Static metadata describing a single API method.
///
/// Created by `declare_api_method_after2!` and collected into a slice by
/// `declare_api_group2!`.
#[derive(Clone, Debug)]
pub struct ApiMethodInfo {
    /// Method name (e.g., `"Ping"`).
    pub name: &'static str,
    /// Group name (e.g., `"WorkerApi"`).
    pub grp: &'static str,
    /// Argument type as a string (e.g., `"()"`).
    pub arg: &'static str,
    /// Return type as a string (e.g., `"()"`).
    pub ret: &'static str,
}

/// Executable implementation of an API method.
///
/// Created by `declare_api_method_impl_after2!` and collected by
/// `implement_api_group2!`. The `func` field is a boxed future wrapper
/// produced by `wrap_impl`.
#[derive(Clone, Debug)]
pub struct ApiMethodImpl {
    /// Method name (e.g., `"Ping"`).
    pub name: &'static str,
    /// Group name (e.g., `"WorkerApi"`).
    pub grp: &'static str,
    /// Callable wrapper that takes a `WorkerMessage` and returns a
    /// `WorkerMessage` future.
    pub func:
        fn(WorkerMessage) -> std::pin::Pin<Box<dyn futures::Future<Output = WorkerMessage> + Send>>,
}

impl ApiMethodImpl {
    /// Returns the fully-qualified method name as `"Group.Method"`.
    pub fn fullname(&self) -> String {
        let b = self.name;
        let a = self.grp;
        format!("{a}.{b}")
    }
}

impl ApiMethodInfo {
    /// Returns the fully-qualified method name as `"Group.Method"`.
    pub fn fullname(&self) -> String {
        let b = self.name;
        let a = self.grp;
        format!("{a}.{b}")
    }
}

/// Macro: declares the zero-sized method type and implements [`ApiMethodDecl`].
///
/// Users typically invoke this indirectly via `declare_api_group2!`.
#[macro_export]
macro_rules! declare_api_method_before2 {
    ($grp:tt, $name:tt, $arg:ty, $ret:ty) => {
        $crate::paste::paste! {
            #[doc = concat!("Zero-sized declaration type for the `", stringify!($name), "` RPC method.")]
            #[derive(Debug, Clone, Copy)]
            pub struct $name;
            impl $crate::api::api_method_macros::ApiMethodDecl for $name {
                const NAME: &str = stringify!($name);
                type Grp = $grp;
                type Arg = $arg;
                type Ret = $ret;
            }
        }
    };
}

/// Macro: produces an [`ApiMethodInfo`] struct literal for a method.
///
/// Used internally by `declare_api_group2!`.
#[macro_export]
macro_rules! declare_api_method_after2 {
    ($grp:tt, $name:tt, $arg:ty, $ret:ty) => {
        $crate::paste::paste! {
                $crate::api::api_method_macros::ApiMethodInfo {
                    name: stringify!($name),
                    grp: stringify!($grp),
                    arg: stringify!($arg),
                    ret: stringify!($ret),
                }
        }
    };
}

/// Macro: declares an API group and all its methods at once.
///
/// Syntax:
/// ```ignore
/// declare_api_group2! {
///     GroupName,
///     [
///         (MethodName, ArgType, RetType),
///         ...
///     ]
/// }
/// ```
///
/// This expands to:
/// - A zero-sized `struct GroupName` implementing [`ApiGroupDecl`] and
///   [`ApiGroupMethods`].
/// - For each method, a zero-sized type implementing [`ApiMethodDecl`].
#[macro_export]
macro_rules! declare_api_group2 {
    ($name:tt, [$(($mname:tt, $arg:ty, $ret:ty),)*]) => {
        #[doc = concat!("Zero-sized declaration type for the `", stringify!($name), "` RPC group.")]
        #[derive(Debug, Copy, Clone)]
        pub struct $name;
        impl $crate::api::api_method_macros::ApiGroupDecl for $name {
            const GROUP: &str = stringify!($name);
        }
        $(
            $crate::declare_api_method_before2!( $name, $mname, $arg, $ret);
        )*

        impl $crate::api::api_method_macros::ApiGroupMethods for $name {
            fn grp_name(&self) -> &'static str {stringify!($name)}
            fn method_infos(&self)
            -> &'static [$crate::api::api_method_macros::ApiMethodInfo]
            {
            &[
                $(
                    $crate::declare_api_method_after2!(
                        $name, $mname, $arg, $ret),
                )*
            ]
            }
        }
    };
}

/// Macro: creates the wrapper functions that adapt a user async function
/// into the worker's `WorkerMessage` -> `WorkerMessage` calling convention.
///
/// Users typically invoke this via `implement_api_group2!`.
#[macro_export]
macro_rules! declare_api_method_impl_before2 {
    ($name:tt, $func:expr) => {
        $crate::paste::paste! {

            #[allow(nonstandard_style)]
            fn [<__ $name __wrapper1>](
                x: <$name as $crate::api::api_method_macros::ApiMethodDecl>::Arg
            ) -> std::pin::Pin<Box<
                dyn $crate::futures::Future<
                    Output=$crate::anyhow::Result<
                        <$name as $crate::api::api_method_macros::ApiMethodDecl>::Ret
                    >
                >+Send
            >> {
                use $crate::futures::FutureExt;
                $func(x).boxed()
            }


            #[allow(nonstandard_style)]
            fn [<__ $name __wrapper_outer>] (msg: $crate::crack_worker::WorkerMessage) -> std::pin::Pin<Box<
                dyn $crate::futures::Future<Output=$crate::crack_worker::WorkerMessage>+Send
            >> {
                <$name as $crate::api::api_method_macros::ApiMethodDecl>::wrap_impl(
                    [<__ $name __wrapper1>],
                    msg,
                )
            }

        }
    };
}

/// Macro: produces an [`ApiMethodImpl`] struct literal referencing the
/// wrapper created by `declare_api_method_impl_before2!`.
///
/// Used internally by `implement_api_group2!`.
#[macro_export]
macro_rules! declare_api_method_impl_after2 {
    ($name:tt, $func:expr) => {
        $crate::paste::paste! {

            $crate::api::api_method_macros::ApiMethodImpl {
                func: [<__ $name __wrapper_outer>],
                name: <$name as $crate::api::api_method_macros::ApiMethodDecl>::NAME,
                grp: <<$name as $crate::api::api_method_macros::ApiMethodDecl>::Grp
                as $crate::api::api_method_macros::ApiGroupDecl>::GROUP,
            }
        }
    };
}

/// Macro: implements [`ApiGroupImpls`] for a group by supplying the
/// implementation functions for each method.
///
/// Syntax:
/// ```ignore
/// implement_api_group2! {
///     GroupName,
///     [
///         (MethodName, async_function),
///         ...
///     ]
/// }
/// ```
///
/// Each `async_function` must have signature
/// `fn(Arg) -> Pin<Box<dyn Future<Output = anyhow::Result<Ret>> + Send>>`.
#[macro_export]
macro_rules! implement_api_group2 {
    ($name:tt, [$(($mname:tt, $arg:expr),)*]) => {
           $(
                $crate::declare_api_method_impl_before2!($mname, $arg);
            )*
        impl $crate::api::api_method_macros::ApiGroupImpls for $name {
            fn method_impls(&self) -> &'static [$crate::api::api_method_macros::ApiMethodImpl] {
            &[
            $(
                $crate::declare_api_method_impl_after2!($mname, $arg),
            )*
                ]
            }
        }
    };
}

#[cfg(test)]
mod tests {
    use super::*;
    #[cfg(target_arch = "wasm32")]
    use wasm_bindgen_test::wasm_bindgen_test as test;

    #[test]
    fn smoke_method_info_and_impl_fullname() {
        let info = ApiMethodInfo {
            name: "Ping",
            grp: "Grp",
            arg: "()",
            ret: "()",
        };
        assert_eq!(info.fullname(), "Grp.Ping");

        let decl = ApiGroupDeclStatic { group: "Grp" };
        assert_eq!(decl.group, "Grp");
    }
}
