use std::{collections::HashMap, sync::Arc};

use _crack_utils::{n0_future, random_u32};

use crate::{
    api::api_method_macros::ApiMethodDecl,
    crack_worker::{WorkerMessage, WorkerPipe},
};

/// Client-side handle for invoking worker API methods.
///
/// Holds a sender to the worker's request channel, an in-flight request
/// map, and a background task that drains the worker's response channel
/// and routes replies back to the waiting callers.
#[derive(Clone)]
pub struct ApiClient {
    /// Sender half of the worker request channel.
    tx: Arc<tokio::sync::mpsc::Sender<WorkerMessage>>,
    /// In-flight request map: msg_id -> oneshot sender for the reply.
    _memory: Arc<tokio::sync::Mutex<ApiClientMemory>>,
    /// Background task that receives responses and wakes up waiters.
    _thread: Arc<_crack_utils::n0_future::task::JoinHandle<anyhow::Result<()>>>,
}

struct ApiClientMemory {
    map: HashMap<u32, MessageLater>,
}

/// Internal holder for the oneshot channel that completes when the
/// worker replies to a specific request ID.
pub struct MessageLater {
    reply_to: tokio::sync::oneshot::Sender<WorkerMessage>,
}

/// Background task that drains the worker's response channel.
///
/// For each `WorkerMessage` received, looks up the corresponding
/// `oneshot::Sender` in `ApiClientMemory` and forwards the message.
/// If no sender is found (stale/duplicate response), logs a warning.
async fn client_thread(
    _memory: Arc<tokio::sync::Mutex<ApiClientMemory>>,
    mut rx_pipe: tokio::sync::mpsc::Receiver<WorkerMessage>,
) -> anyhow::Result<()> {
    while let Some(ret) = rx_pipe.recv().await {
        let ret_id = ret.msg_id;

        let Some(connect) = ({ _memory.lock().await.map.remove(&ret_id) }) else {
            tracing::warn!("got a message back but no known ID, id={}", ret_id);
            continue;
        };
        let _r = connect.reply_to.send(ret);
        if let Err(_e) = _r {
            tracing::info!("Failed to send back worker message: id={}", _e.msg_id);
            continue;
        }
    }
    Ok(())
}

impl ApiClient {
    /// Creates a new `ApiClient` from a `WorkerPipe`.
    ///
    /// Spawns the background `client_thread` to handle responses.
    pub fn new(pipe: WorkerPipe) -> Self {
        let _memory = Arc::new(tokio::sync::Mutex::new(ApiClientMemory {
            map: HashMap::new(),
        }));
        let _memory2 = _memory.clone();
        Self {
            tx: Arc::new(pipe.req_tx),
            _thread: Arc::new(n0_future::task::spawn(client_thread(
                _memory2,
                pipe.resp_rx,
            ))),
            _memory,
        }
    }

    /// Invokes an API method on the worker and awaits the result.
    ///
    /// `T` must implement [`ApiMethodDecl`] (generated by the API macros).
    /// The argument is serialized with `postcard`, sent to the worker, and
    /// the response is deserialized into `T::Ret`.
    ///
    /// # Errors
    /// Returns an error if serialization, channel send, or response
    /// deserialization fails, or if the worker returns an error.
    pub async fn call<T: ApiMethodDecl>(&self, arg: T::Arg) -> anyhow::Result<T::Ret> {
        let arg = postcard::to_stdvec(&arg)?;
        let msg_type = T::fullname();
        let req_id = random_u32();

        let msg = WorkerMessage {
            msg_content: arg,
            msg_id: req_id,
            msg_type,
        };
        let (one_tx, one_rx) = tokio::sync::oneshot::channel::<WorkerMessage>();

        let _ins = {
            let _memory = &mut self._memory.lock().await.map;

            _memory.insert(req_id, MessageLater { reply_to: one_tx })
        };
        self.tx.send(msg).await?;

        let ret = one_rx.await?;
        match ret.msg_type.as_str() {
            "return" => {
                // The worker wraps every successful return in
                // `Result<Ret, String>` (see `wrap_impl`), so decode that and
                // surface an app-level error as an `Err` rather than mis-reading
                // the `Ok` variant tag as the payload.
                let ret: Result<T::Ret, String> = postcard::from_bytes(&ret.msg_content)?;
                ret.map_err(|e| anyhow::anyhow!("{e}"))
            }
            "error_deserialize_arg" => Err(anyhow::anyhow!(
                "worker failed to deserialize arg: {}",
                String::from_utf8_lossy(&ret.msg_content)
            )),
            "error_serialize_ret" => Err(anyhow::anyhow!(
                "worker failed to serialize return: {}",
                String::from_utf8_lossy(&ret.msg_content)
            )),
            _ => Err(anyhow::anyhow!(
                "unexpected worker message type: {}",
                ret.msg_type
            )),
        }
    }
}
