server {
    listen 18080;

    location / {
        proxy_pass http://localhost:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        proxy_hide_header cross-origin-opener-policy;
        proxy_hide_header cross-origin-embedder-policy;

        add_header Cross-Origin-Opener-Policy same-origin;
        add_header cross-origin-opener-policy same-origin;
        add_header Cross-Origin-Embedder-Policy require-corp;
        add_header cross-origin-embedder-policy require-corp;
    }
}